[package]
name = "charming"
description = "A visualization library for Rust"
version = "0.2.4"
edition = "2021"
authors = ["Yuankun Zhang <i@yuankun.me>"]
homepage = "https://github.com/yuankunzhang/echarts-rs"
documentation = "https://github.com/yuankunzhang/echarts-rs"
keywords = ["echarts", "visualization", "chart", "plot"]
categories = ["visualization", "graphics"]
license = "MIT/Apache-2.0"
readme = "../README.md"

[dependencies]
deno_core = { version = "0.195", optional = true }
handlebars = "4.3"
image = { version = "0.24", optional = true }
resvg = { version = "0.35", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = {version = "0.5", optional = true }
serde_with = "3.3.0"
serde_json = "1.0"
serde_v8 = { version = "0.106", optional = true }
wasm-bindgen = { version = "0.2", optional = true }

[dependencies.web-sys]
version = "0.3.64"
optional = true
features = [
    "Window",
    "Document",
    "Element",
]

[features]
ssr = ["deno_core", "image", "resvg", "serde_v8"]
wasm = ["serde-wasm-bindgen", "wasm-bindgen", "web-sys"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]